In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("C:\\Users\\hsesu\\Desktop\\Bigdata project\\Placement_Data_Full_Class.csv")

In [3]:
dataset

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0        1      M  67.00   Others  91.00   Others  Commerce     58.00   
1        2      M  79.33  Central  78.33   Others   Science     77.48   
2        3      M  65.00  Central  68.00  Central      Arts     64.00   
3        4      M  56.00  Central  52.00  Central   Science     52.00   
4        5      M  85.80  Central  73.60  Central  Commerce     73.30   
..     ...    ...    ...      ...    ...      ...       ...       ...   
210    211      M  80.60   Others  82.00   Others  Commerce     77.60   
211    212      M  58.00   Others  60.00   Others   Science     72.00   
212    213      M  67.00   Others  67.00   Others  Commerce     73.00   
213    214      F  74.00   Others  66.00   Others  Commerce     58.00   
214    215      M  62.00  Central  58.00   Others   Science     53.00   

      degree_t workex  etest_p specialisation  mba_p      status    salary  
0     Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1     Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2    Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3     Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4    Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0  
..         ...    ...      ...            ...    ...         ...       ...  
210  Comm&Mgmt     No     91.0        Mkt&Fin  74.49      Placed  400000.0  
211   Sci&Tech     No     74.0        Mkt&Fin  53.62      Placed  275000.0  
212  Comm&Mgmt    Yes     59.0        Mkt&Fin  69.72      Placed  295000.0  
213  Comm&Mgmt     No     70.0         Mkt&HR  60.23      Placed  204000.0  
214  Comm&Mgmt     No     89.0         Mkt&HR  60.22  Not Placed       NaN  

[215 rows x 15 columns]

In [4]:
#Data preprocessing

In [5]:
dataset.isnull().any()

sl_no             False
gender            False
ssc_p             False
ssc_b             False
hsc_p             False
hsc_b             False
hsc_s             False
degree_p          False
degree_t          False
workex            False
etest_p           False
specialisation    False
mba_p             False
status            False
salary             True
dtype: bool

In [6]:
dataset.replace(np.nan,0,inplace=True)

In [7]:
dataset["status"]=dataset["status"].replace('Placed',1)
dataset["status"]=dataset["status"].replace('Not Placed',0)

In [8]:
dataset.head(10)

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   
5      6      M  55.00   Others  49.80   Others   Science     67.25   
6      7      F  46.00   Others  49.20   Others  Commerce     79.00   
7      8      M  82.00  Central  64.00  Central   Science     66.00   
8      9      M  73.00  Central  79.00  Central  Commerce     72.00   
9     10      M  58.00  Central  70.00  Central  Commerce     61.00   

    degree_t workex  etest_p specialisation  mba_p  status    salary  
0   Sci&Tech     No    55.00         Mkt&HR  58.80       1  270000.0  
1   Sci&Tech    Yes    86.50        Mkt&Fin  66.28       1  200000.0  
2  Comm&Mgmt     No    75.00        Mkt&Fin  57.80       1  250000.0  
3   Sci&Tech     No    66.00         Mkt&HR  59.43       0       0.0  
4  Comm&Mgmt     No    96.80        Mkt&Fin  55.50       1  425000.0  
5   Sci&Tech    Yes    55.00        Mkt&Fin  51.58       0       0.0  
6  Comm&Mgmt     No    74.28        Mkt&Fin  53.29       0       0.0  
7   Sci&Tech    Yes    67.00        Mkt&Fin  62.14       1  252000.0  
8  Comm&Mgmt     No    91.34        Mkt&Fin  61.29       1  231000.0  
9  Comm&Mgmt     No    54.00        Mkt&Fin  52.21       0       0.0

In [9]:
dataset.isnull().any()

sl_no             False
gender            False
ssc_p             False
ssc_b             False
hsc_p             False
hsc_b             False
hsc_s             False
degree_p          False
degree_t          False
workex            False
etest_p           False
specialisation    False
mba_p             False
status            False
salary            False
dtype: bool

In [10]:
dataset.dtypes

sl_no               int64
gender             object
ssc_p             float64
ssc_b              object
hsc_p             float64
hsc_b              object
hsc_s              object
degree_p          float64
degree_t           object
workex             object
etest_p           float64
specialisation     object
mba_p             float64
status              int64
salary            float64
dtype: object

In [11]:
#Splitting of dependent and independent variable

In [12]:
x=dataset.iloc[:,1:13].values

In [13]:
x

array([['M', 67.0, 'Others', ..., 55.0, 'Mkt&HR', 58.8],
       ['M', 79.33, 'Central', ..., 86.5, 'Mkt&Fin', 66.28],
       ['M', 65.0, 'Central', ..., 75.0, 'Mkt&Fin', 57.8],
       ...,
       ['M', 67.0, 'Others', ..., 59.0, 'Mkt&Fin', 69.72],
       ['F', 74.0, 'Others', ..., 70.0, 'Mkt&HR', 60.23],
       ['M', 62.0, 'Central', ..., 89.0, 'Mkt&HR', 60.22]], dtype=object)

In [14]:
y=dataset.iloc[:,-2].values

In [15]:
y

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [16]:
#y = y.astype('bool')

In [17]:
y

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [18]:
# Data Preprocessing 

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
lb=LabelEncoder()

In [21]:
x[:,0] = lb.fit_transform(x[:,0])
x[:,2] = lb.fit_transform(x[:,2])
x[:,4] = lb.fit_transform(x[:,4])
x[:,5] = lb.fit_transform(x[:,5])
x[:,7] = lb.fit_transform(x[:,7])
x[:,8] = lb.fit_transform(x[:,8])
x[:,10] = lb.fit_transform(x[:,10])

In [22]:
x

array([[1, 67.0, 1, ..., 55.0, 1, 58.8],
       [1, 79.33, 0, ..., 86.5, 0, 66.28],
       [1, 65.0, 0, ..., 75.0, 0, 57.8],
       ...,
       [1, 67.0, 1, ..., 59.0, 0, 69.72],
       [0, 74.0, 1, ..., 70.0, 1, 60.23],
       [1, 62.0, 0, ..., 89.0, 1, 60.22]], dtype=object)

In [23]:
y[:]=lb.fit_transform(y[:])

In [24]:
y

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [25]:
#Split data into test and train

In [26]:
from sklearn.model_selection import train_test_split 

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0) 

In [28]:
x_train

array([[1, 51.0, 1, ..., 60.0, 1, 60.64],
       [1, 52.0, 0, ..., 62.0, 1, 60.59],
       [1, 76.5, 1, ..., 97.4, 0, 74.01],
       ...,
       [1, 77.0, 1, ..., 80.0, 0, 67.05],
       [1, 63.0, 0, ..., 78.0, 0, 54.55],
       [1, 73.0, 1, ..., 84.0, 1, 52.64]], dtype=object)

In [29]:
x_test

array([[0, 67.0, 0, 70.0, 0, 1, 65.0, 1, 0, 88.0, 1, 71.96],
       [0, 79.0, 0, 76.0, 0, 2, 65.6, 2, 0, 58.0, 1, 55.47],
       [0, 84.0, 1, 75.0, 1, 2, 69.0, 2, 1, 62.0, 1, 62.36],
       [0, 48.0, 0, 51.0, 0, 1, 58.0, 0, 1, 60.0, 1, 58.79],
       [1, 80.0, 1, 80.0, 1, 1, 72.0, 0, 1, 63.79, 0, 66.04],
       [0, 59.0, 0, 62.0, 1, 1, 77.5, 0, 0, 74.0, 1, 67.0],
       [0, 76.0, 0, 70.0, 0, 2, 76.0, 0, 1, 66.0, 0, 64.44],
       [1, 67.0, 1, 63.0, 0, 1, 72.0, 0, 0, 56.0, 1, 60.41],
       [1, 55.0, 1, 49.8, 1, 2, 67.25, 2, 1, 55.0, 0, 51.58],
       [1, 84.0, 1, 79.0, 1, 2, 68.0, 2, 1, 84.0, 0, 66.69],
       [1, 60.4, 0, 66.6, 1, 2, 65.0, 0, 0, 71.0, 1, 52.71],
       [1, 89.4, 1, 65.66, 1, 2, 71.25, 2, 0, 72.0, 1, 63.23],
       [1, 87.0, 0, 74.0, 0, 2, 65.0, 2, 1, 75.0, 1, 72.29],
       [1, 58.0, 1, 61.0, 1, 1, 61.0, 0, 0, 58.0, 1, 53.94],
       [1, 56.6, 0, 64.8, 0, 1, 70.2, 0, 0, 84.27, 0, 67.2],
       [1, 55.68, 1, 61.33, 1, 1, 56.87, 0, 0, 66.0, 1, 58.3],
       [0, 79.0, 1,

In [30]:
y_train

array([0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [31]:
y_test

array([0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1],
      dtype=int64)

In [32]:
#Feature Scaling

In [33]:
from sklearn.preprocessing import MinMaxScaler

In [34]:
sc=MinMaxScaler()

In [35]:
x_train=sc.fit_transform(x_train)

In [36]:
x_test=sc.transform(x_test)

In [37]:
#import seaborn as sns

In [38]:
#sns.pairplot(dataset) 

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,recall_score,f1_score,precision_score,roc_auc_score
from sklearn.model_selection import GridSearchCV

In [40]:
list = []

In [41]:
dict = {}
logr=LogisticRegression()
logr.fit(x_train,y_train)
y_pred=logr.predict(x_test)
dict['Algorithm Model'] = 'Logistic Regression'
dict['Accuracy'] = accuracy_score(y_test,y_pred)
dict['Recall'] = recall_score(y_test,y_pred)
dict['Precision'] = precision_score(y_test,y_pred)
dict['F1 score'] = f1_score(y_test,y_pred)
dict['roc_auc'] = roc_auc_score(y_test,y_pred)
list.append(dict)

In [42]:
#tree = DecisionTreeClassifier()
#tree_param = {
 #   'criterion':['gini','entropy'],
 #   'splitter':['best','random'],  
  #  'max_depth':[3,4,5,6],
  #  'max_features':['auto','log2'],
   # 'random_state':[123]
#}

#grid = GridSearchCV(tree, tree_param, cv=10)
#best_parameter_search = grid.fit(x_train,y_train)
#best_parameter_search.best_params_

In [43]:
dict1 = {}
dt=DecisionTreeClassifier(criterion='entropy',max_depth=5,max_features='auto',random_state=123,splitter='best')
dt.fit(x_train,y_train)
y_pred1=dt.predict(x_test)
dict1['Algorithm Model'] = 'Decision Tree Classisifer'
dict1['Accuracy'] = accuracy_score(y_test,y_pred1)
dict1['Recall'] = recall_score(y_test,y_pred1)
dict1['Precision'] = precision_score(y_test,y_pred1)
dict1['F1 score'] = f1_score(y_test,y_pred1)
dict1['roc_auc'] = roc_auc_score(y_test,y_pred1)
list.append(dict1)




In [44]:
dict2 = {}
rf=RandomForestClassifier(n_estimators=1000,criterion='entropy',random_state=0)
rf.fit(x_train,y_train)
y_pred2=rf.predict(x_test)
dict2['Algorithm Model'] = 'Random Forest'
dict2['Accuracy'] = accuracy_score(y_test,y_pred2)
dict2['Recall'] = recall_score(y_test,y_pred2)
dict2['Precision'] = precision_score(y_test,y_pred2)
dict2['F1 score'] = f1_score(y_test,y_pred2)
dict2['roc_auc'] = roc_auc_score(y_test,y_pred2)
list.append(dict2)


In [45]:
dict3 = {}
knn=KNeighborsClassifier(n_neighbors=5,p=2)
knn.fit(x_train,y_train)
y_pred3=knn.predict(x_test)
dict3['Algorithm Model'] = 'KNN'
dict3['Accuracy'] = accuracy_score(y_test,y_pred3)
dict3['Recall'] = recall_score(y_test,y_pred3)
dict3['Precision'] = precision_score(y_test,y_pred3)
dict3['F1 score'] = f1_score(y_test,y_pred3)
dict3['roc_auc'] = roc_auc_score(y_test,y_pred3)
list.append(dict3)

In [46]:
table = pd.DataFrame(list)
table

Algorithm Model  Accuracy    Recall  Precision  F1 score  \
0        Logistic Regression  0.846154  0.978261   0.833333  0.900000   
1  Decision Tree Classisifer  0.769231  0.891304   0.803922  0.845361   
2              Random Forest  0.784615  0.913043   0.807692  0.857143   
3                        KNN  0.753846  0.913043   0.777778  0.840000   

    roc_auc  
0  0.752288  
1  0.682494  
2  0.693364  
3  0.640732

In [47]:
#y_pred

In [48]:
#y_test

In [49]:
#from sklearn.metrics import accuracy_score

In [50]:
#print("Accuracy:",accuracy_score(y_test,y_pred)*100,"%")